### ISSUE TITLE
Config.App: Qt missing

### ISSUE THREAD

**Issue by BlckCobra64** [VDJartnet/VDJartnet#10]
I'd suggest to either statically link it or deploy instructions/info on installing Qt runtime. Or did I miss something important?

**Error message:**
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Volumes/VOLUME/*/config.app/Contents/MacOS/VDJartnetConfig
  Reason: image not found

**Comment by flumeware** [comment]
The latest version of the plugin v0.1.8 removes the Qt dependancy for the mac version as the config tool uses native api instead. It can be downloaded from the website
https://www.kepler22b.uk/vdjartnet/download.html

**Comment by flumeware** [comment]
The latest version v0.1.12 removes the Qt dependency. It can be downloaded from the website https://www.kepler22b.uk/vdjartnet/download.html

**Comment by BlckCobra64** [comment]
The download of the OSX version results in a broken 1 KByte ZIP file. I tried with 2 different browsers, same result.

**Comment by flumeware** [comment]
fixed

**Comment by BlckCobra64** [comment]
Thank you.
I downloaded it and tested it. Opening the config window works fine on v0.1.12 (OSX)
