### ISSUE TITLE
All windows dll after 10.05.18 are buggy

### ISSUE THREAD

**Issue by bluescreen25** [VDJartnet/VDJartnet#12]
In virtual dj high cpu usage and crashes. 
Last working windows version on 10.05.18 without crashes and low cpu. The config windows work in one instance and come up every time on config button.

After that date all versions for windows are trash. The last version september 2018 the config windows never come up after they went in the background. I must pick from the taskbar . (development backwards)

Sorry but years ago i developed in Delphi (Pascal) and i tested my work and also worked with the user.
On my mind the earlier versions with excluded presets.txt are better to exchange ideas of VDJ-Script with other user. Now the dll file is blown up with included presets.txt.....

**Comment by flumeware** [comment]
The latest version of the software is available from the website https://www.kepler22b.uk/vdjartnet/download.html 
The repositories master branch is not considered stable, releases are made when ready and posted to the website. If you want to use this for DJing I would suggest you use one of the releases from our downloads page, which have received more testing.

**Comment by bluescreen25** [comment]
Latest beta 0.2.1 Release every Time config Button pressed  it creates new Windows. If i went 10 times into config there are  20 Windows in Taskbar. Seems to be a Problem with catching  window handle. 

Compiled windows dll from 10.05.18 seems  to be stable.  I took my own ideas to presents and helping photos into.
http://www.cave-live.info/VDJArtnet.zip

**Comment by flumeware** [comment]
The opening of multiple copies of the config window is the expected behaviour for that version. This has been changed in the current development version, which are not yet stable.

With regards to your changes please open a pull request if you would like them to be considered for merging.

**Comment by aDifferentJT** [comment]
We believe that these issues will be resolved by the time 1.0.0 is released, we currently are very close to a release candidate, for now please use the versions on the website as they are the only ones marked as having been at all tested.
