### ISSUE TITLE
string is longer than limit while parsing lines of presets.txt

### ISSUE THREAD

**Issue by bluescreen25** [VDJartnet/VDJartnet#14]
[presets.txt](https://github.com/VDJartnet/VDJartnet/files/2516152/presets.txt)

After line 53 is end.  I think we need another routine. because with extensive scripts in presets.txt we need more chars..

**Comment by flumeware** [comment]
The issue may be due to the compiler limiting the length of string literals which would affect the compiled in presets. As a workaround it is possible load presets using an include option in the config file. 

Inside your VDJArtnet.conf file if you put a line starting with `@p` followed by a space and then the path to a preset file the plugin will load all of the lines from that file into the list of presets. 

This is in addition to the compiled in presets, so if you revert the presets.txt file in the src directory to the default one from the repository you should avoid this issue

The preset parser has a large limit on the length of the line, this limit is related to the total amount of memory in the computer and cannot be changed.

**Comment by aDifferentJT** [comment]
I’m also going to try to remove the limit on compiled presets

**Comment by bluescreen25** [comment]
Thanks for fast response. I am working with  older version from 05/2018. The Windows 32bit is stable and does not have the function @c and @p to import 2nd presets file. Don't know why, but I cannot compile the newest versions to release 32bit. I become a lot of errors while compiling. My main question is why did you included the presets? Is it faster ? Or?
Do you have a tip to compile newer versions on Visual Studio 17 ? So I can test it,too while creating the scripts.

**Comment by flumeware** [comment]
what is the sha1 of the commit you are able to compile successfully, since I am not sure which version of the code you are actually running at the moment.

**Comment by bluescreen25** [comment]
![win32bit](https://user-images.githubusercontent.com/43250376/47530306-81e35780-d8aa-11e8-97c4-5d4e4a863ac7.jpg)

**Comment by bluescreen25** [comment]
![screen](https://user-images.githubusercontent.com/43250376/47531778-d983c200-d8ae-11e8-86fb-4a9b1ccb913c.jpg)
![github25_10_18](https://user-images.githubusercontent.com/43250376/47530923-4fd2f500-d8ac-11e8-90e5-7dc682acc8e1.jpg)

Screenshot Compile Github 25_10_18 version , not working

**Comment by aDifferentJT** [comment]
Yeah, I have identified the issue there and am working to fix it

**Comment by aDifferentJT** [comment]
I can confirm that in the current HEAD this issue is fixed, can I check whether you are happy for the presets.txt that you posted above to be included in trunk and licensed under GPL with the rest of the code. (Though it may be sensible to license defaultPresets.txt under something more permissive like MIT or BSD).

**Comment by bluescreen25** [comment]
I dowloaded last source and wanted to compile. Downloaded Haskell platform,too.  Compiling to Win32 Release made StringLinker.exe but then it seems to be , that the input file is not found. Please help, to get it work. Is Teamviewer a possibilty to get my Development Enviroment to get work compiling right ? My ID 839 663 167 
![compile](https://user-images.githubusercontent.com/43250376/48312285-bb0b0f80-e5ac-11e8-8d57-eb38dfb3a418.jpg)
![haskell](https://user-images.githubusercontent.com/43250376/48312286-bb0b0f80-e5ac-11e8-93e1-e3a4696a70cb.jpg)
![stringlinker](https://user-images.githubusercontent.com/43250376/48312287-bb0b0f80-e5ac-11e8-842e-190636e180fc.jpg)
![tlog](https://user-images.githubusercontent.com/43250376/48312288-bba3a600-e5ac-11e8-96c8-10e762c0b6f2.jpg)
![vdjartnet vcxproj](https://user-images.githubusercontent.com/43250376/48312289-bba3a600-e5ac-11e8-869b-6caabb224720.jpg)

**Comment by aDifferentJT** [comment]
You need to install NASM from https://www.nasm.us/ if that doesn't work i'll be happy to look closer at you development environment.

**Comment by bluescreen25** [comment]
Yes..... works now....must copy nasm.exe after installation otherwise dev did not find it while compiling.
![nasm](https://user-images.githubusercontent.com/43250376/48312687-f6104180-e5b2-11e8-81c6-eacd1f0529e9.jpg)

**Comment by bluescreen25** [comment]
Top !!!
Actual dll works. Will test and give you feedback.
Here my actual long list of presets for free use.  In QLC+ Forum i made some macros to get the channel values from plugin gets together. Have a look on.
![vdjartnet_win32_actual](https://user-images.githubusercontent.com/43250376/48312816-8c913280-e5b4-11e8-9e2a-e3244cd007a0.jpg)
[defaultPresets.txt](https://github.com/VDJartnet/VDJartnet/files/2569351/defaultPresets.txt)

**Comment by flumeware** [comment]
Just to confirm are you happy to release your presets under either the MIT or BSD licence, as the presets file will be licensed separately from the main program. The main program remains under the GPL licence.

**Comment by bluescreen25** [comment]
> 
> 
> Just to confirm are you happy to release your presets under either the MIT or BSD licence, as the presets file will be licensed separately from the main program. The main program remains under the GPL licence.

What must i do to do that ? You can use it in a way you like.

**Comment by flumeware** [comment]
I think that is sufficient, we just needed you to confirm that you are happy for it to be released under one of those licences, saying that we are free to use it however we like is sufficient for that purpose.

Thank you
