### ISSUE TITLE
Config Error 

### ISSUE THREAD

**Issue by Michilson02** [VDJartnet/VDJartnet#3]
(Beta Tester)

When I try to install it I can get it into VDJ8 but it gives me a error about missing libgcc_s_sjlj-1.dll. when I click the config tab in the Plugin. 

I also have a Tap button setup for QLC+ and have it set to artnet1 channel 500 but it doesn't seem to be doing anything. 

Can you please look into missing DLL and walk me through getting this setup. 

Windows 7 laptop and VDJ 8 Ver 8.2

QLC+ 4.10.3 Sending to 127.0.0.1 IP for same machine running both VDj & QLC

Testing on QLC+ (with 254 used Channels)

**Comment by aDifferentJT** [comment]
The Config tool is still being developed, I'm literally sorting the windows version as we speak, please try the latest version of VDJartnet.dll as found in CompiledBinaries

**Comment by aDifferentJT** [comment]
As for the setup please can you post your config.txt file

**Comment by Michilson02** [comment]
Config.txt I haven't modified the original.  I see Line 500 (Seems to be sending Beat Info) I have QLC+ looking at Artnet universe 1 Channel 500 for the TAP input but don't see anything happening.

Do I not have something set correctly? Can you clarify what the Channel 500 is doing and what modifications need to be made. I'll test actual inputs tonight too. 

Any documentation on how to configure this might help a lot thanks guy's! Super excited to be part of this testing for you. (Please stick with me I'm not a coder so I might need a little help to get this working. :) But I'll do my best to give you feed back and input. Thanks


```
127.0.0.1
001~var $artnet 1 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
002~var $artnet 2 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
003~var $artnet 3 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
004~var $artnet 4 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
005~var $artnet 5 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
006~var $artnet 6 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
007~var $artnet 7 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
008~var $artnet 8 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
009~var $artnet 9 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
010~var $artnet 10 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
011~var $artnet 11 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
012~var $artnet 12 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
013~var $artnet 13 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
014~var $artnet 14 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
015~var $artnet 15 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
016~var $artnet 16 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
017~var $artnet 17 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
018~var $artnet 18 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
019~var $artnet 19 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
020~var $artnet 20 ? set $VDJartnetSend 255 : set $VDJartnetSend 0
500~param_greater get_beat_bar 12.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 25% ? set $VDJartnetSend 0 : param_greater get_beat_bar 37.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 50% ? set $VDJartnetSend 0 : param_greater get_beat_bar 62.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 75% ? set $VDJartnetSend 0 : param_greater get_beat_bar 87.5% ? set $VDJartnetSend 255 : set $VDJartnetSend 0
501~
502~
503~
504~
505~
506~
507~
508~
509~
510~
511~
512~
```

**Comment by JTProjectFun** [comment]
the 500 channel definition is missing the separator character ~

Infact most lines are.  Each line has to start with a 3 digit number (e.g. 007, 123, 510) then a separator tilde ~  and then the VDJscript.

Here's my config.txt which works fine;

```
127.0.0.1
001~var artnet 1 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
002~var artnet 2 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
003~var artnet 3 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
004~var artnet 4 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
005~var artnet 5 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
006~var artnet 6 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
007~var artnet 7 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
008~var artnet 8 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
009~var artnet 9 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
010~var artnet 10 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
011~var artnet 11 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
012~var artnet 12 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
013~var artnet 13 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
014~var artnet 14 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
015~var artnet 15 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
016~var artnet 16 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
017~var artnet 17 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
018~var artnet 18? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
019~var artnet 19 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
020~var artnet 20 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
021~var artnet 21 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
022~var artnet 22 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
025~var artnet 25 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
026~var artnet 26 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
027~var artnet 27 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
028~var artnet 28 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
029~var artnet 29 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
030~var artnet 30 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
100~var artnet 100 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
101~var artnet 101 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
050~var artnet 200 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
150~var artnet 150 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
151~var artnet 151 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
152~var artnet 152 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
153~var artnet 153 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
154~var artnet 154 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
155~var artnet 155 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
156~var artnet 156 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
200~param_greater get_beat_bar 12.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 25% ? set $VDJartnetSend 0 : param_greater get_beat_bar 37.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 50% ? set $VDJartnetSend 0 : param_greater get_beat_bar 62.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 75% ? set $VDJartnetSend 0 : param_greater get_beat_bar 87.5% ? set $VDJartnetSend 255 : set $VDJartnetSend 0
210~var artnet 210 ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
211~var artnet 211 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
212~var artnet 212 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
213~var artnet 213 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
214~var artnet 214 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
215~var artnet 215 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
216~var artnet 216 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
217~var artnet 217 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
218~var artnet 218 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
219~var artnet 219 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
220~var artnet 220 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
221~var artnet 221 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
501~var artnet 501 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
511~var artnet 511 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0
520~var artnet 520 ? is_audible deck active ? set $VDJartnetSend 255 : set $VDJartnetSend 0 : set $VDJartnetSend 0

```

**Comment by JTProjectFun** [comment]
Ah nuts!  Github is messing up the pasting of the config.txt contents!  ARGHH!.

**Comment by aDifferentJT** [comment]
GitHub is mangling the files by interpreting them as Markdown code, I suggest you paste them into gists or upload the actual files

**Comment by flumeware** [comment]
if you use the insert code option in the editor it should just let you paste the config
eg
`001~test`

**Comment by aDifferentJT** [comment]
Please check the packets received on the Input/Output tab in QLC+

**Comment by JTProjectFun** [comment]
So the line for channel 500 isn't missing the separator.  I can't see what's up - maybe something wrong with the vdjscript?

**Comment by JTProjectFun** [comment]
Tip: Use an artnet monitoriing program such as artnetominator for checking the artnet path.  When a deck is playing you *should* see channel 500 going between 0 & 255 in time with the music.  If you do that & find it works, then the problem is with your QLC+ configuration

**Comment by Michilson02** [comment]
The `500~param_greater get_beat_bar 12.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 25% ? set $VDJartnetSend 0 : param_greater get_beat_bar 37.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 50% ? set $VDJartnetSend 0 : param_greater get_beat_bar 62.5% ? set $VDJartnetSend 255 : param_greater get_beat_bar 75% ? set $VDJartnetSend 0 : param_greater get_beat_bar 87.5% ? set $VDJartnetSend 255 : set $VDJartnetSend 0` Is stock not modified from the Zip download package. I dont see any Packets being sent from the VDJ to IP 127.0.0.1

**Comment by Michilson02** [comment]
so not sure whats not correct but hopefully we can figure it out.

**Comment by aDifferentJT** [comment]
Replace the dll with the latest from compiledbinaries

**Comment by Michilson02** [comment]
I'll give that a try and report back :)

**Comment by Michilson02** [comment]
when I load the DLL in compiledbinaries folder I get a new Error Missing MSVCP140.dll

**Comment by Michilson02** [comment]
Jhornsby I think right now it's not even running the plugin. I'm on Windows 7 laptop and VDJ 8 Ver 8.2

QLC+ 4.10.3 Sending to 127.0.0.1 IP for same machine running both VDj & QLC

I'm getting errors trying to run either the zip package dll missing libgcc_s_sjlj-1.dll everything seems okay but doesn't do anything

Or if I over right that with the dll from compiledbinaries will not even launch the plugin

I get a not compatible error and missing MSVCP140.dll

So my guess is that the plugin for whatever reason isn't running to send beat data on channel 500.

**Comment by aDifferentJT** [comment]
Are you using Windows 32 bit or 64 bit?

**Comment by aDifferentJT** [comment]
With the latest version of the plugin I switched the config tool to the CLR however the CLR cannot be statically linked so I had to switch to dynamic linking, this means that you'll need the VC++ Redistributable which can be obtained at [https://www.visualstudio.com/downloads/](https://www.visualstudio.com/downloads/) and scrolling down to Other Tools and Frameworks or alternatively use the direct download link [https://go.microsoft.com/fwlink/?LinkId=746572](https://go.microsoft.com/fwlink/?LinkId=746572)

**Comment by Michilson02** [comment]
I'll have to check tonight I believe it's 32 bit. But I am not sure. It gives me a incompatible error in VDJ8 however. I'm curious how you guys have this working? are you all on Mac?

**Comment by aDifferentJT** [comment]
I believe that installing the VC++ redistributable will fix it, I'm on Mac however the other two have it working fine on windows

**Comment by Michilson02** [comment]
Okay well that is a issue shouldn't need to download anything to run a VDJ plugin. Might need to add other things to the package for this to work or reformat the code to work within VDJ. Again I'm not a coder and trying to test this for you guys. But I'm not aware of needing to download any additional things for VDJ plugins. Normally just download the plugin and it installs to the correct place. I dont know if the VDJ team fixes things like this during the submittal  process. Just a thought if you plan to distribute this to all the VDJ users.

**Comment by aDifferentJT** [comment]
Yes, I know, there are ways to have stuff like this install automatically however for now it does require manual installation

**Comment by Michilson02** [comment]
Okay I will give that a shot tonight and again report back. Thanks!

**Comment by Michilson02** [comment]
okay guys I have download the VC++ redistributable and I am still not getting any beat info from VDJ on artnet. 

I also installed the Artnetominator and do not see anything on Channel 500

**Comment by aDifferentJT** [comment]
Is it working now?

**Comment by Michilson02** [comment]
Seems to be working. Thanks I still need to test actually sending Input commands but the Beat send seems to be working.

**Comment by aDifferentJT** [comment]
Ah ok, what was the problem and what was the solution that worked?
