### ISSUE TITLE
Stop more than once instance of the plugin running

### ISSUE THREAD

**Issue by JTProjectFun** [VDJartnet/VDJartnet#4]
If more than one copy of the vdjartnet plugin resides in the VDJ autostart folder, multiple instances of the plugin can run resulting in utter artnet chaos.  Add a check to ensure only one runs.

**Comment by aDifferentJT** [comment]
This is actually harder than it appears because the VDJscript API doesn't allow for atomic operations

**Comment by JTProjectFun** [comment]
Maybe just use a variable then? If variable set already, just stop.

**Comment by aDifferentJT** [comment]
VDJ variables aren't atomic and variables in my code aren't shared between instances

**Comment by aDifferentJT** [comment]
We have added something that should fix it
