### ISSUE TITLE
Suggested Feature

### ISSUE THREAD

**Issue by Michilson02** [VDJartnet/VDJartnet#6]
Guy's I'm still working to figure this out but it appears that when you have lights set to run chases on BPM into on QLC+ when the song ends it appears the lights default to keep changing based on the previous BPM. I was wondering if we can get a code that if there isn't a active deck playing it will either default to a really high Beat count (2-3 min) to stall the lights changing. 

Just a thought of a feature. Other than that so far seems kool! Thanks Guys!

**Comment by aDifferentJT** [comment]
[https://github.com/VDJartnet/VDJartnet-Config-Files](https://github.com/VDJartnet/VDJartnet-Config-Files) on there in the presets.txt there is a Play command, you could nest this with the beat command if you want

**Comment by aDifferentJT** [comment]
`play ? param_greater get_beat_bar 12.5% ? set $VDJartnetsend 255 : param_greater get_beat_bar 25% ? set $VDJartnetsend 0 : param_greater get_beat_bar 37.5% ? set $VDJartnetsend 255 : param_greater get_beat_bar 50% ? set $VDJartnetsend 0 : param_greater get_beat_bar 62.5% ? set $VDJartnetsend 255 : param_greater get_beat_bar 75% ? set $VDJartnetsend 0 : param_greater get_beat_bar 87.5% ? set $VDJartnetsend 255 : set $VDJartnetsend 0 : set $VDJartnetsend 0`

**Comment by aDifferentJT** [comment]
That would stop the beat thing when it stops changing but that wouldn't actually help, the beat thing stops anyway, the problem is that the QLC+ beat timer widget doesn't stop the beats when the input stops by design.

**Comment by Michilson02** [comment]
Can we set the Beat that gets sent really high when a song stops?

**Comment by aDifferentJT** [comment]
We don't sent a bpm, we send a pulse every beat

**Comment by aDifferentJT** [comment]
`play ? set $VDJartnetsend 255 : set $VDJartnetsend 0` use that command to send a signal when playing or `play ? set $VDJartnetsend 0 : set $VDJartnetsend 255` to send a signal when you stop, you could tie the latter to a QLC+ script that stays `stop <function>`
