### ISSUE TITLE
Need VDJ pro version ?

### ISSUE THREAD

**Issue by cedric5133** [VDJartnet/VDJartnet#7]
I install your plugin in my VDJ but it does not seems to work. I have no error but nothing happens. Do i need the pro version ? 

Thanks.

**Comment by flumeware** [comment]
Hello which version of the plugin have you downloaded? 

If it was v0.1.1 which is a devlopment release rather than stable have you installed Microsoft Visual C++ Redistributable for Visual Studio 2017?

I am not sure if the pro version of virtual DJ is required for the plugins to work.

**Comment by flumeware** [comment]
you probably need a pro licence in order to use plugins
