### ISSUE TITLE
Monitor config.txt for changes and automatically reload it

### ISSUE THREAD

**Issue by BlckCobra64** [VDJartnet/VDJartnet#8]
I have tested your VDJ plugin on my Mac and it works great. I have a feature request anyway to make it easier/faster to test new light settings/scripts changes.

The config.txt is red during VDJ startup. When it changes one has to quit and restart VDJ.
I'd suggest to monitor the config.txt for changes and automatically reload it in case.

**Comment by aDifferentJT** [comment]
Monitoring for changes isn't trivial, it could check periodically but you can use the refresh button in the plugin gui (click the settings wheel next to VDJartnet in the plugin drop down)

**Comment by BlckCobra64** [comment]
Thank you for this hint. Unfortunately I can not find the plugin gui anywhere. Where is it supposed to be?
