### ISSUE TITLE
DMX channels running wild when using "VDJartnet" plugin name in a script

### ISSUE THREAD

**Issue by BlckCobra64** [VDJartnet/VDJartnet#9]
When trying to script a button to display the plugin GUI quickly I had my lights running wild (it sends data to all configured (config.txt) DMX channels.

Repro: edit a custom button,
add the following script `effect_show_gui VDJartnet`

Same happens when you use OnInit function in the keyboard mapping for example.

**Comment by sh6397** [comment]
Hi, are you using the Artnet output to directly control lights or are you using it as a control to DMX software which then in tern controls the lights?

**Comment by aDifferentJT** [comment]
Please install the latest version from https://www.kepler22b.uk/vdjartnet/download.html and confirm if the problem persists

**Comment by BlckCobra64** [comment]
I am using it to control a DMX software (QLC+)

**Comment by BlckCobra64** [comment]
The problem has changed with v0.1.12 (OSX)
When I add a custom button using the script below, all output to QLC+ via artnet is halted.
I am using VDJ V8.2 b3846

Custom button: `effect_show_gui VDJartnet`

**Comment by aDifferentJT** [comment]
Can I confirm if the config.txt uses `get_constant` or `set $VDJartnetSend`

**Comment by BlckCobra64** [comment]
It uses `set $VDJartnetSend`

**Comment by aDifferentJT** [comment]
Does anything happen when you press the button, and when is output halted, when the button is created or when it is pressed?

**Comment by BlckCobra64** [comment]
It is enough when the button with this script exists or when it is created.

**Comment by aDifferentJT** [comment]
Please could you send your skin

**Comment by aDifferentJT** [comment]
I believe it is fixed in the latest release

**Comment by BlckCobra64** [comment]
It's not solved :(
It still stops any output to QLC+ as soon as I add a script using the plugin name "VDJartnet" (script see above).
Using V0.1.2 the buttons/menu for VDJArtnet showed up, now this does not work anymore (V0.2.0).
The skin I use is "GianB 4 Decks V3.7" 
(Sorry for the delayed answer, I was DJing last night)

**Comment by aDifferentJT** [comment]
I have tested it and I believe that 0.2.1 does fix the issue

**Comment by aDifferentJT** [comment]
You need to use `deck master effect_show_gui "VDJartnet"` in order for it to work now as otherwise you are trying to create another instance of the plugin for the currently selected deck, that will no longer break the plugin but the button will not work

**Comment by BlckCobra64** [comment]
@nixCodeX Thank you for this hint. I works fine now. Great work. 👍
